### ISSUE TITLE
[Feature Request] Support Debian Bullseye (11) and Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by gotmax23** [cloudlinux/kcare-uchecker#35]
This project does not currently work on Debian Bullseye (11) or Ubuntu Focal (20.04).

**Debian Bullseye (11):**

```shell
> curl -s -L https://kernelcare.com/uchecker | sudo python
Distro `debian11.0` is not supported
```

**Ubuntu Focal (20.04):**

```shell
> curl -s -L https://kernelcare.com/uchecker | sudo python
Distro `ubuntu-focal` is not supported
```

Support for Focal should be a high priority, given that it is the current Ubuntu LTS release. There is already support for the previous Ubuntu LTS release (Bionic/18.04).

On the Debian side, Bullseye is currently the testing distribution; however, it will be released and become Debian Stable in the next couple months.

**Comment by histrio** [comment]
Hi @gotmax23 !
It's done!
Thank you for your interest in the tool

**Comment by gotmax23** [comment]
Thank you for the fix. There still are issues, however. It still does not work at all on Debian Bullseye.

**Debian Bullseye (11):**

> curl -s -L https://kernelcare.com/uchecker | sudo python
Distro `debian11.0` is not supported

On Ubuntu Focal, it reports that several processes are ` linked to the libc-2.31.so that is not up to date.` even though I updated all packages on the system and rebooted.

**Comment by histrio** [comment]
Yep, I've miss `debian11.0` and it should be OK now. 
Could you please provide more information about `ubuntu-focal` case? Do you have some additional repositories attached?
Please, send us part of [debug output](https://github.com/cloudlinux/kcare-uchecker#troubleshooting) where the message about glibc appears?
