### ISSUE TITLE
Broken (bad?) link in  README.md

### ISSUE THREAD

**Issue by j75** [cloudlinux/kcare-uchecker#39]
```The project is part of kernelcare.com - livepatching ...```
The corresponding link https://kernelcare.com has an error on Firefox:
```
Secure Connection Failed
The connection to the server was reset while the page was loading.... 
```
Shouldn't the link actually be https://tuxcare.com/ ?

**Comment by histrio** [comment]
Hi @j75 
Uchecker has become a part of tuxcare indeed, but https://kernelcare.com is still a reliable URL for the project.
URL was changed.
Thank you!
