### ISSUE TITLE
Support more Linux distributions

### ISSUE THREAD

**Issue by huda-kh** [cloudlinux/kcare-uchecker#56]
This [web page](https://docs.tuxcare.com/live-patching-services/) states that uchecker is compatible with all modern linux distros but I've just tried on Ubuntu 22.04 and Mint 21.3 and neither was supported.

**Comment by histrio** [comment]
Hi @huda-kh ! I will check and get back to you.

**Comment by histrio** [comment]
I believe we have support for ubuntu-jammy. Could you please attach an output for
```
curl -s -L https://kernelcare.com/uchecker | sudo LOGLEVEL=debug python
```
?

**Comment by huda-kh** [comment]
> I believe we have support for ubuntu-jammy. Could you please attach an output for
> 
> ```
> curl -s -L https://kernelcare.com/uchecker | sudo LOGLEVEL=debug python
> ```
> 
> ?

Sorry, that's embarrassing.. it's working now!
